#!/bin/tcsh -f

if ($# != 3) then
	echo "arg1 - text file"
	echo "arg2 - pos list"
	echo "arg3 - end syllables list"
	exit(-1)
endif

rm temp_2 temp_1
./scripts/stanford-postagger.sh models/tamil_pos.tagger $1 > tagged_text

set start = 1
set count = `cat $2 |wc -l`
while ($start <= $count)
	set pos = `cat $2 |head -$start |tail -1`
	sed -i "s@$pos@$pos ,/RD_PUNC@g" tagged_text
	@ start++
end

./scripts/detagging tagged_text
cp text_detagged temp_2
sed -i 's/ ,/,/g' temp_2
sed -i 's/,,/,/g' temp_2

set count1 = `grep -o "," temp_2 |wc -l`
@ count1++
set start1 = 1

while ($start1 <= $count1)
	set phrase_cnt = `cat temp_2 |cut -d "," -f$start1 |wc -w`
	set phrase_cnt1 = `echo "$phrase_cnt - 1" |bc`
	set phrase = `cat temp_2 |cut -d "," -f$start1`
	if ($phrase_cnt >= 6) then
		set st = 1
		while ($st <= $phrase_cnt)
			set wrd = `echo $phrase |cut -d " " -f$st`
			echo $wrd > lists/word1
			perl scripts/vuv.pl lists/word1
		        perl scripts/ortho_to_phonetic1.pl lists/out_word lists/phoneset_all phone
		        perl scripts/syllable_from_char.pl phone lists/phoneset_uyir lists/phoneset_mei lists/phoneset_uyirmei > syllables

		        set syl = `cat syllables |tail -1`
		        set flg = `grep -w $syl $3 |wc -l`
			set word = `cat lists/out_word`
		        if ($flg != 0 && $st < $phrase_cnt1) then
		                echo -n $wrd", " >> temp_1
		        else
		                echo -n $wrd" " >> temp_1
		        endif
			@ st++	
		end
	else
		#if ($start1 == $count1) then
                echo -n $phrase >> temp_1
                #else
                #echo -n $phrase", " >> temp_1
                #endif	
	endif
	echo -n ", " >> temp_1
@ start1++
end
sed -i 's/ ,/,/g' temp_1
sed -i 's/\.,/./g' temp_1
